In [1]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /gdrive


In [2]:
import pandas as pd
import numpy as np

In [3]:
path='/gdrive/My Drive/ML:March2020/data/'
data=pd.read_csv(path+"emails.csv")
data.head(10)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1
5  Subject: great nnews  hello , welcome to medzo...     1
6  Subject: here ' s a hot play in motion  homela...     1
7  Subject: save your money buy getting this thin...     1
8  Subject: undeliverable : home based business f...     1
9  Subject: save your money buy getting this thin...     1

In [4]:
data.shape

(5728, 2)

In [5]:
x=data['text']
y=data['spam']

In [6]:
y

0       1
1       1
2       1
3       1
4       1
       ..
5723    0
5724    0
5725    0
5726    0
5727    0
Name: spam, Length: 5728, dtype: int64

In [7]:
print("spam count:{},label is {}".format(sum(y==1),'1'))
print("not-spam count:{},label is {}".format(sum(y==0),'0'))

spam count:1368,label is 1
not-spam count:4360,label is 0


In [8]:
x=x.values.tolist()
type(x)

list

In [9]:
from nltk.corpus import stopwords

import nltk
import re
nltk.download('punkt')
nltk.download('stopwords')
import string
from nltk.tokenize import RegexpTokenizer

tokenizer = RegexpTokenizer('\w+')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [10]:
def tok(x):
  return (tokenizer.tokenize(x))

In [11]:
sw=stopwords.words('english')
sw

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [12]:
def process_text(text):
  pattern = '[0-9]'
  
  data = [re.sub(pattern,'' , i) for i in text]
  
  pattern1= '_'

  data = [re.sub(pattern1, '' , i) for i in data]

  return data

In [14]:
data=process_text(x)
data

["Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  m

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
Vectorizer = CountVectorizer(analyzer='word', tokenizer=tok, stop_words=sw, ngram_range=(1, 1))

In [17]:
Vector_x= Vectorizer.fit_transform(data)
print(Vector_x.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
Vector_x.shape

(5728, 33563)

In [19]:
Vectorizer.get_feature_names()

['aa',
 'aaa',
 'aaaenerfax',
 'aadedeji',
 'aagrawal',
 'aal',
 'aaldous',
 'aaliyah',
 'aall',
 'aanalysis',
 'aaron',
 'aawesome',
 'ab',
 'aba',
 'abacha',
 'abacus',
 'abahy',
 'abaixo',
 'abandon',
 'abandoned',
 'abandonment',
 'abargain',
 'abarr',
 'abattoir',
 'abb',
 'abbas',
 'abbestellen',
 'abbott',
 'abbreviated',
 'abbreviation',
 'abc',
 'abcsearch',
 'abdalla',
 'abdallat',
 'abdelnour',
 'abdul',
 'abdulla',
 'abdullah',
 'abeis',
 'abel',
 'abello',
 'abels',
 'aber',
 'abernathy',
 'abetted',
 'abeyance',
 'abf',
 'abhay',
 'abide',
 'abidjan',
 'abiiity',
 'abilene',
 'abilities',
 'ability',
 'abilmesi',
 'abit',
 'abitibi',
 'abklaeren',
 'abl',
 'able',
 'abler',
 'abliged',
 'ablx',
 'ably',
 'abn',
 'abnegate',
 'abnormal',
 'abnormality',
 'aboard',
 'abolish',
 'abondantly',
 'abook',
 'aboriginal',
 'abormalities',
 'abort',
 'abortive',
 'abouts',
 'aboutthis',
 'aboutus',
 'aboutvenita',
 'aboveground',
 'abovenet',
 'abovetelefax',
 'abqewvbgf',
 'abr',

In [20]:
print(Vector_x.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
Vector_x.shape

(5728, 33563)

In [22]:
from sklearn.feature_extraction.text import TfidfTransformer
Tfid = TfidfTransformer()

In [23]:
Vector_x = Tfid.fit_transform(Vector_x)
print(Vector_x.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(Vector_x,np.array(y), test_size=0.25, random_state=2)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((4296, 33563), (1432, 33563), (4296,), (1432,))

## Bernoulli

In [26]:
from sklearn.naive_bayes import BernoulliNB
classifier1=BernoulliNB()
classifier1.fit(x_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [27]:
y_pred=classifier1.predict(x_test)

In [28]:
print(np.array(y_pred.shape))

[1432]


In [29]:
targets=['Not spam','Spam']
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,target_names=targets))

[[1060    8]
 [  34  330]]
              precision    recall  f1-score   support

    Not spam       0.97      0.99      0.98      1068
        Spam       0.98      0.91      0.94       364

    accuracy                           0.97      1432
   macro avg       0.97      0.95      0.96      1432
weighted avg       0.97      0.97      0.97      1432



## Gaussian

In [32]:
from sklearn.naive_bayes import GaussianNB
classifier2 = GaussianNB()
classifier2.fit(x_train.toarray(), y_train)

y_pred2= classifier2.predict(x_test.toarray())

print(np.array(y_pred2.shape))

targets = ['Not Spam', 'Spam']
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2, target_names=targets))

[1432]
[[1059    9]
 [  61  303]]
              precision    recall  f1-score   support

    Not Spam       0.95      0.99      0.97      1068
        Spam       0.97      0.83      0.90       364

    accuracy                           0.95      1432
   macro avg       0.96      0.91      0.93      1432
weighted avg       0.95      0.95      0.95      1432



## Complement

In [33]:
from sklearn.naive_bayes import ComplementNB
classifier3 = ComplementNB()
classifier3.fit(x_train.toarray(), y_train)

y_pred3= classifier2.predict(x_test.toarray())

targets = ['Not Spam', 'Spam']
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred3))
print(classification_report(y_test, y_pred3, target_names=targets))

[[1059    9]
 [  61  303]]
              precision    recall  f1-score   support

    Not Spam       0.95      0.99      0.97      1068
        Spam       0.97      0.83      0.90       364

    accuracy                           0.95      1432
   macro avg       0.96      0.91      0.93      1432
weighted avg       0.95      0.95      0.95      1432



## New input

In [34]:
s=[]
s.append(input())

Hi balaji,  Due to recent events, certification providers such as CompTIA and AWS are now offering online proctoring for exams. This means not only can you prepare for certifications online but you can also take the actual certification exam online!   Cybrary Insider Pro has everything you need to pass your exam with video courses, hands-on labs, and practice tests tied directly to key learning objectives. I encourage you to take a look at the learning content we offer for these certification providers below:


In [36]:
s= process_text(s)
Vector_email= Vectorizer.transform(s)
Vector_email.shape

(1, 33563)

In [37]:
tfid_email = Tfid.transform(Vector_email)
pred =classifier1.predict(tfid_email)
pred

array([0])

In [38]:
if (pred[0]==0):
  print('The mail is not a spam!')

else:
    print('It is a spam!!')

The mail is not a spam!
