In [0]:
import numpy as np
list1 = [0,1,2,3,4,5]
array1d=np.array(list1)

In [0]:
print(type(array1d))

<class 'numpy.ndarray'>


In [0]:
print(array1d)

[0 1 2 3 4 5]


In [0]:
#list1+2

In [0]:
array1d+2

array([2, 3, 4, 5, 6, 7])

In [0]:
list2=[[1,2,3],[4,5,6],[7,8,9]]
array2d=np.array(list2)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
array=np.array(list2,dtype='float')
array

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [0]:
array.astype('int')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
array.astype('str')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U32')

In [0]:
array.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

size and shape of an numpy array

In [0]:
list2=[[1,2,3,4],[5,6,7,8],[9,0,2,3]]
array2=np.array(list2,dtype='float')
array2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [9., 0., 2., 3.]])

In [0]:
print('shape:',array2.shape)
print('datatype:',array2.dtype)
print('Size: ', array2.size)
print('Num dimensions:',array2.ndim)

shape: (3, 4)
datatype: float64
Size:  12
Num dimensions: 2


extract specific items from the array

In [0]:
array2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [9., 0., 2., 3.]])

In [0]:
array2[:2,:2]

array([[1., 2.],
       [5., 6.]])

In [0]:
b=array2>2
b

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False,  True]])

In [0]:
array2[b]

array([3., 4., 5., 6., 7., 8., 9., 3.])

reverse the rows and the whole array

In [0]:
array2[::-1,]

array([[9., 0., 2., 3.],
       [5., 6., 7., 8.],
       [1., 2., 3., 4.]])

In [0]:
array2[::-1,::-1]

array([[3., 2., 0., 9.],
       [8., 7., 6., 5.],
       [4., 3., 2., 1.]])

representing missing values and infinte

In [0]:
array2[1,1]=np.nan
array2[1,2] = np.inf
array2

array([[ 1.,  2.,  3.,  4.],
       [ 5., nan, inf,  8.],
       [ 9.,  0.,  2.,  3.]])

In [0]:
missing_bool = np.isnan(array2)|np.isinf(array2)
array2[missing_bool]=-1
array2

array([[ 1.,  2.,  3.,  4.],
       [ 5., -1., -1.,  8.],
       [ 9.,  0.,  2.,  3.]])

compute mean ,min,max on the ndarray

In [0]:
print("Mean value : ", array2.mean())
print("Max value : ", array2.max())
print("Min value : ", array2.min())

Mean value :  2.9166666666666665
Max value :  9.0
Min value :  -1.0


In [0]:
print("column wise min:",np.amin(array2,axis=0))
print("row wise min:",np.amin(array2,axis=1))

column wise min: [ 1. -1. -1.  3.]
row wise min: [ 1. -1.  0.]


In [0]:
np.cumsum(array2)

array([ 1.,  3.,  6., 10., 15., 14., 13., 21., 30., 30., 32., 35.])

creating a new array from an existing array

In [0]:
array2a=array2[:2,:2]
array2a[:1,:1]=200
array2

array([[200.,   2.,   3.,   4.],
       [  5.,  -1.,  -1.,   8.],
       [  9.,   0.,   2.,   3.]])

In [0]:
array2b=array2[:2,:2].copy()
array2b[:1,:1]=201
array2

array([[200.,   2.,   3.,   4.],
       [  5.,  -1.,  -1.,   8.],
       [  9.,   0.,   2.,   3.]])

reshaping and flattering multidim array

In [0]:
array2.reshape(4,3)

array([[200.,   2.,   3.],
       [  4.,   5.,  -1.],
       [ -1.,   8.,   9.],
       [  0.,   2.,   3.]])

difference btw flatten() and ravel()

In [0]:
array2.flatten()

array([200.,   2.,   3.,   4.,   5.,  -1.,  -1.,   8.,   9.,   0.,   2.,
         3.])

In [0]:
b1 = array2.flatten()  
b1[0] = 100 
array2

array([[200.,   2.,   3.,   4.],
       [  5.,  -1.,  -1.,   8.],
       [  9.,   0.,   2.,   3.]])

In [0]:
b2 = array2.ravel()  
b2[0] = 99 
array2

array([[99.,  2.,  3.,  4.],
       [ 5., -1., -1.,  8.],
       [ 9.,  0.,  2.,  3.]])

create seq ,repetions and random numbers using numpy


In [0]:
print(np.arange(6))  
print(np.arange(0, 30))  
print(np.arange(0, 30, 2))  
print(np.arange(20, 0, -2))

[0 1 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[20 18 16 14 12 10  8  6  4  2]


In [0]:
np.linspace(start=1, stop=50, num=15, dtype=int)

array([ 1,  4,  8, 11, 15, 18, 22, 25, 29, 32, 36, 39, 43, 46, 50])

In [0]:
np.set_printoptions(precision=2) 
np.logspace(start=1, stop=50, num=15, base=10) 

array([1.00e+01, 3.16e+04, 1.00e+08, 3.16e+11, 1.00e+15, 3.16e+18,
       1.00e+22, 3.16e+25, 1.00e+29, 3.16e+32, 1.00e+36, 3.16e+39,
       1.00e+43, 3.16e+46, 1.00e+50])

In [0]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [0]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

create repeating sequence

In [0]:
a=[1,2,3]
print('Tile:',np.tile(a,3))
print('Repeat:',np.repeat(a,3))

Tile: [1 2 3 1 2 3 1 2 3]
Repeat: [1 1 1 2 2 2 3 3 3]


generating random numbers

In [0]:
print(np.random.rand(2,2))
print(np.random.randn(2,2))
print(np.random.randint(0, 10, size=[2,2]))
print(np.random.random())
print(np.random.random(size=[2,2]))
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1]))

[[0.51 0.67]
 [0.94 0.33]]
[[-1.15 -1.91]
 [ 0.28  1.06]]
[[7 2]
 [5 1]]
0.7650320786634408
[[0.75 0.1 ]
 [0.57 0.54]]
['u' 'e' 'e' 'u' 'o' 'u' 'e' 'u' 'u' 'e']
['a' 'a' 'u' 'e' 'o' 'i' 'a' 'a' 'e' 'o']


In [0]:
rn = np.random.RandomState(50)
print(rn.rand(3,3))

[[0.49 0.23 0.26]
 [0.4  0.38 1.  ]
 [0.41 0.77 0.76]]


In [0]:
np.random.seed(30)
print(np.random.rand(3,3))

[[0.64 0.38 0.66]
 [0.16 0.96 0.35]
 [0.99 0.24 0.59]]


getting the unique items and the counts

In [0]:
np.random.seed(30)
arr_rand = np.random.randint(0, 20, size=20)
print(arr_rand)

[ 5  5 13 13 12  2 17 14  3  9  7  1 17 13  3 18 18  6 12 16]


In [0]:
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

Unique items :  [ 1  2  3  5  6  7  9 12 13 14 16 17 18]
Counts       :  [1 1 2 2 1 1 1 2 3 1 1 2 2]


getting index locations that satisfies a given condition using np.where

In [0]:
import numpy as np
arr_rand = np.array([9,9,7,54,34,56,6,3,5,6,3])
print("Array: ", arr_rand)
index_gt5 = np.where(arr_rand > 5)
print("Positions where value > 5: ", index_gt5)

Array:  [ 9  9  7 54 34 56  6  3  5  6  3]
Positions where value > 5:  (array([0, 1, 2, 3, 4, 5, 6, 9]),)


In [0]:
arr_rand.take(index_gt5)

array([[ 9,  9,  7, 54, 34, 56,  6,  6]])

In [0]:
np.where(arr_rand>5,'gt5','le5')

array(['gt5', 'gt5', 'gt5', 'gt5', 'gt5', 'gt5', 'gt5', 'le5', 'le5',
       'gt5', 'le5'], dtype='<U3')

In [0]:
print('position of max value:',np.argmax(arr_rand))
print('position of min value:',np.argmin(arr_rand))

position of max value: 5
position of min value: 7


import and export data as csv

In [0]:
np.set_printoptions(suppress=True)
path='https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'
data=np.genfromtxt(path,delimiter=",",skip_header=1,filling_values=888,dtype="float")
data[:3]

array([[  18. ,    8. ,  307. ,  130. , 3504. ,   12. ,   70. ,    1. ,
         888. ],
       [  15. ,    8. ,  350. ,  165. , 3693. ,   11.5,   70. ,    1. ,
         888. ],
       [  18. ,    8. ,  318. ,  150. , 3436. ,   11. ,   70. ,    1. ,
         888. ]])

handling datasets that has both numberes and text columns


In [0]:
data2 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None)
data2[:3]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


array([(18., 8, 307., 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i8'), ('f2', '<f8'), ('f3', '<i8'), ('f4', '<i8'), ('f5', '<f8'), ('f6', '<i8'), ('f7', '<i8'), ('f8', 'S38')])

In [0]:
np.savetxt('out.csv',data,delimiter=",")

save and load numpy objects

In [0]:
np.save("array.npy",array2d)

In [0]:
a=np.load('array.npy')
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


concatenate two numpy arrays columnwise and row wise

In [0]:
c=np.ones([3,3])
d=np.zeros([3,3])
print(c)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
np.concatenate([c,d],axis=1)
np.vstack([c,d])  #h=horizontal stack v= vertical stack
np.c_[c,d]  #.c gives colums stack .r gives rows stack

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [0]:
np.r_[[2,3,4],9,9,[7,8,9]]

array([2, 3, 4, 9, 9, 7, 8, 9])

sorting a numpy array based on one or more columns 


In [0]:
array = np.random.randint(1,11, size=[8, 4])
array

array([[ 7,  1,  8,  5],
       [ 3,  2,  8,  2],
       [10,  9,  6, 10],
       [ 8, 10,  2,  9],
       [ 8,  5,  7,  9],
       [10,  7,  1,  8],
       [ 6, 10,  4,  2],
       [ 5,  3,  4, 10]])

In [0]:
np.sort(array,axis=0)

array([[ 3,  1,  1,  2],
       [ 5,  2,  2,  2],
       [ 6,  3,  4,  5],
       [ 7,  5,  4,  8],
       [ 8,  7,  6,  9],
       [ 8,  9,  7,  9],
       [10, 10,  8, 10],
       [10, 10,  8, 10]])

sorting a numpy array based on 1 column using argsort

In [0]:
x = np.array([23,42,53,64,76,87])
sort_index = np.argsort(x)
print(sort_index)

[0 1 2 3 4 5]


In [0]:
x[sort_index] # assending 

array([23, 42, 53, 64, 76, 87])

In [0]:
sort_index_1col = array[:, 0].argsort()
array[sort_index_1col]

array([[ 3,  2,  8,  2],
       [ 5,  3,  4, 10],
       [ 6, 10,  4,  2],
       [ 7,  1,  8,  5],
       [ 8, 10,  2,  9],
       [ 8,  5,  7,  9],
       [10,  9,  6, 10],
       [10,  7,  1,  8]])

In [0]:
array[sort_index_1col[::-1]]

array([[10,  7,  1,  8],
       [10,  9,  6, 10],
       [ 8,  5,  7,  9],
       [ 8, 10,  2,  9],
       [ 7,  1,  8,  5],
       [ 6, 10,  4,  2],
       [ 5,  3,  4, 10],
       [ 3,  2,  8,  2]])

sorting a numpy array based on 2 or more columns 

In [0]:
lexsorted_index=np.lexsort((array[:,1],array[:,0]))
array[lexsorted_index]

array([[ 3,  2,  8,  2],
       [ 5,  3,  4, 10],
       [ 6, 10,  4,  2],
       [ 7,  1,  8,  5],
       [ 8,  5,  7,  9],
       [ 8, 10,  2,  9],
       [10,  7,  1,  8],
       [10,  9,  6, 10]])

working on  dates

In [0]:
date64 = np.datetime64('2020-02-12 23:10:10')
date64

numpy.datetime64('2020-02-12T23:10:10')

In [0]:
dt64 = np.datetime64(date64, 'D')
dt64

numpy.datetime64('2020-02-12')

In [0]:
tenminutes = np.timedelta64(10, 'm') 
tenseconds = np.timedelta64(10, 's')
tennanoseconds = np.timedelta64(10, 'ns')
tenmicroseconds=np.timedelta64(10,'ms')
print('Add 10 days: ', dt64 + 10)
print('Add 10 minutes: ', dt64 + tenminutes)
print('Add 10 seconds: ', dt64 + tenseconds)
print('Add 10 nanoseconds: ', dt64 + tennanoseconds)
print('Add 10 microseconds:',dt64 + tenmicroseconds)

Add 10 days:  2020-02-22
Add 10 minutes:  2020-02-12T00:10
Add 10 seconds:  2020-02-12T00:00:10
Add 10 nanoseconds:  2020-02-12T00:00:00.000000010
Add 10 microseconds: 2020-02-12T00:00:00.010


In [0]:
np.datetime_as_string(dt64)

'2020-02-12'

In [0]:
print('Date: ', dt64)
print("Is it a business day?: ", np.is_busday(dt64))  
print("Add 3 business days, rolling forward to nearest biz day: ", np.busday_offset(dt64, 3, roll='forward'))  
print("Add 3 business days, rolling backward to nearest biz day: ", np.busday_offset(dt64, 3, roll='backward'))  

Date:  2020-02-12
Is it a business day?:  True
Add 3 business days, rolling forward to nearest biz day:  2020-02-17
Add 3 business days, rolling backward to nearest biz day:  2020-02-17


creating an sequence of dates

In [0]:
dates = np.arange(np.datetime64('2020-02-07'), np.datetime64('2020-02-17'))
print(dates)
np.is_busday(dates)

['2020-02-07' '2020-02-08' '2020-02-09' '2020-02-10' '2020-02-11'
 '2020-02-12' '2020-02-13' '2020-02-14' '2020-02-15' '2020-02-16']


array([ True, False, False,  True,  True,  True,  True,  True, False,
       False])

convert numpy.datetime64 as datetime.datetime

In [0]:
import datetime
dt=dt64.tolist()
dt

datetime.date(2020, 2, 12)

In [0]:
print('Year: ', dt.year)  
print('Day of month: ', dt.day)
print('Month of year: ', dt.month)  
print('Day of Week: ', dt.weekday()) # tue

Year:  2020
Day of month:  12
Month of year:  2
Day of Week:  2


vectorize-make a scalar function work on vectors

In [0]:
def foo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2
print('x = 23 returns ', foo(23))
print('x = 25 returns ', foo(25))

x = 23 returns  529
x = 25 returns  625


In [0]:
foo_v = np.vectorize(foo, otypes=[float])
print('x = [23,14,45] returns ', foo_v([23,14,45]))
print('x = [[23,14,45], [1, 2, 3]] returns ', foo_v([[23,14,45], [1, 2, 3]]))

x = [23,14,45] returns  [ 529.    7. 2025.]
x = [[23,14,45], [1, 2, 3]] returns  [[ 529.    7. 2025.]
 [   1.    1.    9.]]


apply a function column wise or row wise

In [0]:
np.random.seed(100)
array_x = np.random.randint(1,10,size=[4,4])
array_x

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [0]:
def max_minus_min(x):
    return np.max(x) - np.min(x)

In [0]:
print('Row wise: ', np.apply_along_axis(max_minus_min, 1, arr=array_x))

Row wise:  [5 7 3 8]


In [0]:
print('Column wise: ', np.apply_along_axis(max_minus_min, 0, arr=array_x))

Column wise:  [7 8 6 5]


find the location to insert so the array with remain sorted

In [0]:
x = np.arange(7)
print('Where should 7 be inserted?: ', np.searchsorted(x, 7))
print('Where should 7 be inserted (right)?: ', np.searchsorted(x, 7, side='right'))

Where should 7 be inserted?:  7
Where should 7 be inserted (right)?:  7


In [0]:
lst = range(50)
probs = np.random.random(50); probs /= probs.sum() 
%timeit lst[np.searchsorted(probs.cumsum(), np.random.random())]
%timeit np.random.choice(lst, p=probs)

The slowest run took 14.46 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.93 µs per loop
The slowest run took 4.46 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 32 µs per loop


In [0]:
array = np.arange(9) 
print('1d: ', array)
array_col = array[:, np.newaxis]
print('array_col shape: ', array_col.shape)
print(array_col)
array_row = array[np.newaxis, :]
print('array_row shape: ', array_row.shape)
print(array_row)

1d:  [0 1 2 3 4 5 6 7 8]
array_col shape:  (9, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
array_row shape:  (1, 9)
[[0 1 2 3 4 5 6 7 8]]


digitize

In [0]:
x = np.arange(30)
bins = np.array([0, 4, 7, 9])
np.digitize(x, bins)

array([1, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4])

clip

In [0]:
np.clip(array, 3, 8)

array([3, 3, 3, 3, 4, 5, 6, 7, 8])

histogram and bincount

In [0]:
x = np.array([0,0,0,1,1,1,1,2,2,2,2,3,3,3,3])
np.bincount(x)
counts, bins = np.histogram(x, [0, 2, 4, 6, 8])
print('Counts: ', counts)
print('Bins: ', bins)

Counts:  [7 8 0 0]
Bins:  [0 2 4 6 8]


excercise

Create a 1D array of numbers from 0 to 9

In [0]:
array = np.arange(9) 
print('1d: ', array)

1d:  [0 1 2 3 4 5 6 7 8]


How to create a boolean array?

In [37]:
list2=[[1,1,1],[1,1,1],[1,1,1]]
array2d=np.array(list2)
array2d
boolean=array2d>0
boolean

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Extract all odd numbers from arr

In [38]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
answer = (arr[arr%2==1])
print (answer)

[1 3 5 7 9]


Replace all odd numbers in arr with -1

In [32]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in range(0,len(arr)):
  if arr[i]%2==1:
    arr[i]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Convert a 1D array to a 2D array with 2 rows

In [40]:
x=np.arange(10)
x
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

How to stack two arrays vertically?

In [47]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Stack the arrays a and b horizontally

In [49]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])